# Copyright (C) 2026 College WiFi Management Project
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=College WiFi Management System
LUCI_DESCRIPTION:=Web-based WiFi management for educational institutions with student authentication, quota management, and network monitoring
LUCI_DEPENDS:=+luci-base +luci-mod-admin-full
LUCI_PKGARCH:=all

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=College WiFi Team

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
